# AUTOGENERATED! DO NOT EDIT! File to edit: gradio.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% gradio.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% gradio.ipynb 3
learn = load_learner('brutalism_or_modernism.pkl')

# %% gradio.ipynb 4
categories = ('brutalism', 'modernism')

def classify_image(image):
    pred, idx, probs = learn.predict(image)
    return dict(zip(categories, map(float, probs)))

# %% gradio.ipynb 6
image = gr.components.Image()
label = gr.components.Label()
examples = ['images/brutalism.jpg', 'images/modernism.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
